### ISSUE TITLE
PointCutMix results on our new benchmark

### ISSUE THREAD

**Issue by jiachens** [cuge1995/PointCutMix#10]
Dear Authors,

Thank you so much for this nice repo. We recently proposed a new corruption robustness benchmark called ModelNet40-C and test PointCutMix on several corruptions from our dataset. We find that PointCutMix-R is robust to "noise" corruptions and overall performs very well.
Github repo: https://github.com/jiachens/ModelNet40-C
Paper link: https://arxiv.org/abs/2201.12296

I wonder if you can mention our benchmark and dataset in your repo to highlight the results. Thank you!

**Comment by cuge1995** [comment]
Thanks for the great work, we will highlight the results soon.

**Comment by jiachens** [comment]
再次感谢~
能请问一下你们paper中 point cloud 可视化是用的什么library嘛
