### ISSUE TITLE
emd install problem

### ISSUE THREAD

**Issue by PaulTHong** [cuge1995/PointCutMix#11]
Hey, I try to install "emd" as the instruction "python setup.py install", then it raises the cuda dismatch error as below:

File "/root/anaconda3/lib/python3.9/distutils/command/build_ext.py", line 340, in run
self.build_extensions()
File "/root/anaconda3/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 404, in build_extensions
self._check_cuda_version()
File "/root/anaconda3/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 781, in _check_cuda_version
raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
RuntimeError:
The detected CUDA version (10.1) mismatches the version that was used to compile
PyTorch (11.3). Please make sure to use the same CUDA versions.

My installed cuda version of torch is 11.3. Does this information mean the demanded cuda of your provided emd package is 10.1? But my friend installs with 11.3 version cuda's torch, he succeeds. Is there higher cuda version emd codebase? Or how should I do? Thank you very much!

**Comment by cuge1995** [comment]
Thanks for your interest. I think you can refer to this [issue](https://github.com/cuge1995/PointCutMix/issues/3)
