### ISSUE TITLE
Integrating a new model (classifier)

### ISSUE THREAD

**Issue by daniellawton99** [cuge1995/PointCutMix#12]
Hi. Looking at the code it seems there is no special constraint on the type of model used as a classifier.
It seems that I only need to make sure that the forward method returns the "prob" & "feat" (where "feat" can be None as in DGCNN).
Am I correct?
Thanks!

**Comment by cuge1995** [comment]
Yes, you are right.
For more model support, I recommend [ModelNet40-C](https://github.com/jiachens/ModelNet40-C)
