### ISSUE TITLE
 ImportError: /amax/PointCutMixmain/models/rscnn_utils/_ext/pointnet2/_pointnet2.so: undefined symbol: state

### ISSUE THREAD

**Issue by wangxin-fighting** [cuge1995/PointCutMix#14]
Hello, I tried your code. When I input the command ''python train_pointcutnix_k.py  --model rscnn_kcutmix'' to run the rscnn model, the following error occurs:  ImportError:  /media/ amax/PointCutMixmain/models/rscnn_utils/_ext/pointnet2/_pointnet2.so: undefined symbol: state       Can you tell me how to solve it, I look forward to your reply. Thank you very much!

**Comment by cuge1995** [comment]
I recommend you check out the newest point cloud repo [ModelNet40-C](https://github.com/jiachens/ModelNet40-C), which is well-designed.

**Comment by wangxin-fighting** [comment]
May I ask if you could share the modelnet40-c dataset? I always fail to download using that readme method!
