### ISSUE TITLE
Code source

### ISSUE THREAD

**Issue by PaulTHong** [cuge1995/PointCutMix#2]
Hey,
    I'd like to ask how long will this code be released? After the review of ICML2021? Thank you very much.

**Comment by cuge1995** [comment]
We are catching up with the deadline recently and have added a lot of experiments. After the deadline, it should be open source soon. The time is about February.

**Comment by PaulTHong** [comment]
OK，thanks! And good luck for ICML2021.

**Comment by cuge1995** [comment]
Thank you for your attention.
