### ISSUE TITLE
[installation details] CUDA_HOME environment variable is not set

### ISSUE THREAD

**Issue by DbrRoxane** [cuge1995/PointCutMix#3]
Hi,

I followed the instruction in the readme but had this error during the `python setup.py install`
`CUDA_HOME environment variable is not set. Please set it to your CUDA install root.`

I solved all those problem but report them in order to propose little changes into the README

I recretated an conda environment and this time downloaded the packages with conda, with
` conda install pytorch-gpu=1.3.1 torchvision cudatoolkit=10.0 -c pytorch`

Then, I have added the CUDA_HOME environment variable with ` export CUDA_HOME=/usr/local/cuda-10.1`

Training is running now (except that with my NVIDIA GEFORCE RTX 2060 I had to reduce the BS to 8 instead of 16)

Thanks for the great repo!

**Comment by cuge1995** [comment]
Thanks for your interest and contribution.
