### ISSUE TITLE
evaluation script

### ISSUE THREAD

**Issue by sheshap** [cuge1995/PointCutMix#6]
Hi @cuge1995,

Very interesting work. 
I have a couple of questions.
1) May I please know if the reported results in the paper are from the tests that happen during training or did you use a separate test script?
2) You have mentioned 91.7% as a baseline for RSCNN. Did you try to recreate RSCNN results or is it from the PointAugment paper(From the RSCNN paper I couldn't find 91.7 as baseline)?

Thanks in advance.

**Comment by cuge1995** [comment]
1. We report the best test result during training.
2. The acc of RSCNN without voting is lower than the original paper, and our baseline also close to 91.7
